### ISSUE TITLE
Compilation error under linux 64 bit and R-mkl

### ISSUE THREAD

**Issue by iagomosqueira** [iagomosqueira/FLasher#51]
_From @poldokim on June 9, 2016 7:40_

When I try to compile FLash packages I have this error:

R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

`* installing *source* package ‘FLash’ ...`
`** libs`
`g++ -I/usr/include/R/ -DNDEBUG  -D_FORTIFY_SOURCE=2   -I../inst/include -fpic  -O3 -m64 -I/opt/intel/composerxe/linux/mkl/include  -c FLCoreClasses.cpp -o FLCoreClasses.o`
`g++ -I/usr/include/R/ -DNDEBUG  -D_FORTIFY_SOURCE=2   -I../inst/include -fpic  -O3 -m64 -I/opt/intel/composerxe/linux/mkl/include  -c FLashDLL.cpp -o FLashDLL.o`
`FLashDLL.cpp: In function ‘SEXPREC* fwd_adolc_FLBiol(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:`
```
FLashDLL.cpp:83:14: error: cannot convert ‘bool’ to ‘SEXP {aka SEXPREC*}’ in return
       return false;
              ^~~~~
```
`FLashDLL.cpp: In function ‘SEXPREC* fwd_adolc_FLBiols(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:`
```
FLashDLL.cpp:133:14: error: cannot convert ‘bool’ to ‘SEXP {aka SEXPREC*}’ in return
       return false;
              ^~~~~
```
```
FLashDLL.cpp:139:14: error: cannot convert ‘bool’ to ‘SEXP {aka SEXPREC*}’ in return
       return false;
              ^~~~~
```
```
/usr/lib64/R/etc/Makeconf:141: recipe for target 'FLashDLL.o' failed
make: *** [FLashDLL.o] Error 1
```
`ERROR: compilation failed for package ‘FLash’`

Do you have any suggestion?

_Copied from original issue: flr/FLash#3_

**Comment by iagomosqueira** [comment]
Hi,



It compiles fine for me in Linux (Ubuntu 14.04) using gcc 4.8.4. What version of gcc do you have? (ggc -v)





---- On Thu, 09 Jun 2016 09:40:04 +0200 poldokim &lt;notifications@github.com&gt;wrote ---- 




When I try to compile FLash packages I have this error:

R version 3.3.0 (2016-05-03) -- "Supposedly Educational"

 Copyright (C) 2016 The R Foundation for Statistical Computing

 Platform: x86_64-pc-linux-gnu (64-bit)


* installing *source* package ‘FLash’ ...

 ** libs

 g++ -I/usr/include/R/ -DNDEBUG -D_FORTIFY_SOURCE=2 -I../inst/include -fpic -O3 -m64 -I/opt/intel/composerxe/linux/mkl/include -c FLCoreClasses.cpp -o FLCoreClasses.o

 g++ -I/usr/include/R/ -DNDEBUG -D_FORTIFY_SOURCE=2 -I../inst/include -fpic -O3 -m64 -I/opt/intel/composerxe/linux/mkl/include -c FLashDLL.cpp -o FLashDLL.o

 FLashDLL.cpp: In function ‘SEXPREC* fwd_adolc_FLBiol(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:


FLashDLL.cpp:83:14: error: cannot convert ‘bool’ to ‘SEXP {aka SEXPREC*}’ in return return false; ^~~~~ 
FLashDLL.cpp: In function ‘SEXPREC* fwd_adolc_FLBiols(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)’:

FLashDLL.cpp:133:14: error: cannot convert ‘bool’ to ‘SEXP {aka SEXPREC*}’ in return return false; ^~~~~ 
FLashDLL.cpp:139:14: error: cannot convert ‘bool’ to ‘SEXP {aka SEXPREC*}’ in return return false; ^~~~~ 
/usr/lib64/R/etc/Makeconf:141: recipe for target 'FLashDLL.o' failed make: *** [FLashDLL.o] Error 1 
ERROR: compilation failed for package ‘FLash’

Do you have any suggestion?

**Comment by iagomosqueira** [comment]
_From @poldokim on June 9, 2016 12:51_

`$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.1.1 20160501 (GCC) 
`
But R was compiled with Intel MKL (to increase computational speed)

**Comment by iagomosqueira** [comment]
I haven't tried compiling with MKL or the latest gcc. We use the same 
versions as R uses to ensure compatibility.

We are moving to a new version of FLash, currently in alpha but already 
compiling. Repository is at

https://github.com/iagomosqueira/FLasher

It is based on Rcpp and cppAD, so it should have less problems compiling 
across platforms and compilers. It does work with both gcc 4.8.4 and clang.

Do let us know if you try compiling it. It is still missing a few bits 
in the R side and a complete example, but should be there in a little while.

**Comment by iagomosqueira** [comment]
Forgot to add, you will need specific versions of both FLCore and FLFishery

library(devtools)
install_github("iagomosqueira/FLFishery")
install_github("flr/FLCore", ref="NewFLBiol")

**Comment by iagomosqueira** [comment]
_From @poldokim on June 13, 2016 7:7_

Thanks a lot! New libraries compiles fine!

**Comment by iagomosqueira** [comment]
Good to know. It is still missing functionality, but it is progressing 
fairly quickly.

**Comment by iagomosqueira** [comment]
_From @slarge on September 5, 2016 14:56_

Trying to get FLash(er) to compile on my x86-64 Windows 7 machine. I have used the following approach (from above)

`library(devtools)
install_github("iagomosqueira/FLFishery")
install_github("flr/FLCore", ref="NewFLBiol")
install_github("iagomosqueira/FLasher")
`

FLFishery loads without issue. 
FLCore yields the following error:
Error in stop(github_error(request)) : 404: Not Found (404)

FLasher strikes out with the following error:
make: *** [FLCatch.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="FLasher.dll" OBJECTS="FLCatch.o FLFishery.o FLQuant_base.o FLQuant_multidim.o FLStock.o RcppExports.o fwdBiol.o fwdControl.o fwdSR.o operating_model.o rcpp_hello_world.o solver.o tests_FLCatch.o tests_FLFishery.o tests_FLQuant.o tests_FLQuantAD.o tests_FLQuant_multidim.o tests_FLStock.o tests_arithmetic_operators.o tests_fwdBiol.o tests_fwdControl.o tests_fwdSR.o tests_operatingModel.o tests_profiling.o tests_solver.o"' had status 2
ERROR: compilation failed for package 'FLasher'

FLash strikes out, too, but I assume it has something to do with the Windows 7 x64.

Suggestions on how to continue?

**Comment by iagomosqueira** [comment]
The new FLBiol class is now on master, so you will need to do

```
library(devtools)
install_github("flr/FLCore")
install_github("iagomosqueira/FLFishery")
install_github("iagomosqueira/FLasher")
```

which works here (R 3.3.1 on Linux, gcc version 4.8.4.

FLash only works on 32 bit, due to the old version of Adol-C. We are not upgrading it and have moved to develop FLasher instead.

I won't be able to test on a Windows 7 machine until later in the week. To make sure we try on the same setup, what version of Rtools are you using?

**Comment by iagomosqueira** [comment]
_From @slarge on September 6, 2016 11:28_

Just tried your suggestion. FLCore and FLFishery load without issue. FLasher still fails. I'm using RTools34. Perhaps the following output is useful.


`Sys.getenv()['PATH']`
PATH                           C:\Program Files\R\R-3.3.1\bin\x64;C:\RBuildTools\3.3\bin;C:\RBuildTools\3.3\mingw_32\bin;C:\Program
                               Files\Broadcom\Broadcom
                               802.11;C:\ProgramData\Oracle\Java\javapath;c:\Program Files
                               (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS
                               Client\;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\...

`Sys.which("gcc.exe")`
                                    gcc.exe 
"C:\\RBUILD~1\\3.3\\mingw_32\\bin\\gcc.exe" 

`system('g++ -v')`
Thread model: posix
gcc version 4.9.3 (i686-posix-dwarf, Built by MinGW-W64 project)

**Comment by iagomosqueira** [comment]
Thanks. I can test this tomorrow. Last time I tried with Rtools 3.4 it 
did compile and load.

**Comment by iagomosqueira** [comment]
Moved issue to iagomosqueira/FLasher

**Comment by iagomosqueira** [comment]
I am testing it in Windows 7, R 3.3.1, Rtools 3.4.0.1962 and it compiles and loads OK. Only difference I see is that I have R installed in c:/R to avoid paths with spaces. what you succeeded compiling any other package with C code?

**Comment by slarge** [comment]
I reinstalled R3.3.1 to c:/R and FLasher is still not compiling. I installed and loaded Rcpp to test if I am able to compile C code, so I assume yes? If not, a suggestion for a different package is appreciated. Just to double check I tried the above in base R and RStudio... and both result in the same errors as above. gcc is not explicitely listed in my PATH, could this be an issue? If so, how should I add gcc to the PATH. Thanks again for your help.

**Comment by iagomosqueira** [comment]
What error message do you get when building FLasher?

Can you try placing Rtools before R in the PATH?

E:\>SET PATH
Path=c:\Rtools\bin;c:\Rtools\mingw_64\bin;c:\R\R-3.3.1\bin;C:\Windows\system32;C
:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C
:\Program Files (x86)\MiKTeX 2.9\miktex\bin\
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

I will also send you by email a compiled package to check if it installs and runs.

**Comment by slarge** [comment]
Hi Iago,
 I've had time to look at this again after some time...

I have set the path order using the Windows "environmental variables"
options and in Command Prompt, the path is specified as:

C:\Rtools\bin;C:\Rtools\mingw_64\bin;C:\RBuildTools\3.3\bin;C:\RBuildTools\3.3\mingw_64\bin;C:\R\R-3.3.1\bin;

However, when I use R Sys.getenv()['PATH'], the order is not preserved:

 C:\R\R-3.3.1\bin\x64;c:\Rtools\bin;c:\Rtools\mingw_64\bin;C:\Rtools\bin;C:\Rtools\mingw_64\bin;C:\RBuildTools\3.3\bin;C:\RBuildTools\3.3\mingw_64\bin;C:\R\R-3.3.1\bin;

Further, when I try to install FLasher,
via install_github("iagomosqueira/FLasher"), I get the following error:

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"C:/R/R-33~1.1/include" -DNDEBUG
 -I"D:/Profiles/Scott/My Documents/R/win-library/3.3/Rcpp/include"
-I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include   -O2 -Wall
 -mtune=core2 -c FLCatch.cpp -o FLCatch.o
c:/Rtools/mingw_32/bin/g++: not found
make: *** [FLCatch.o] Error 127

When I run system('g++ -v'), I get:

Using built-in specs.
COLLECT_GCC=c:\Rtools\mingw_64\bin\G__~1.EXE
COLLECT_LTO_WRAPPER=c:/Rtools/mingw_64/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.3/lto-wrapper.exe
Target: x86_64-w64-mingw32,

So i'm not sure what is going on...

If you can send me the compiled package via email, I will try that. Thanks
in advance for any help you can offer...

SL

**Comment by iagomosqueira** [comment]
What is in C:\Rtools\bin? I fear the various paths leading to mingw might be to blame.

C:\Rtools\bin;C:\Rtools\mingw_64\bin;C:\RBuildTools\3.3\bin;C:\RBuildTools\3.3\mingw_64\bin;

I will send you a compiled package for you to test. I am creating it in Windows 7, R 3.3.1 as stated above.

**Comment by slarge** [comment]
Hi Iago,
 I am new to modifying the path environmental variables, so thanks for the
tip - it seems that I had a few versions of Rtools cluttering things up. I
uninstalled RBuildTools from an older RTools version and reinstalled the
new rtools34. Now I get a new set of errors:

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"C:/R/R-33~1.1/include" -DNDEBUG
 -I"D:/Profiles/Scott/My Documents/R/win-library/3.3/Rcpp/include"
-I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include   -O2 -Wall
 -mtune=core2 -c FLCatch.cpp -o FLCatch.o
In file included from ../inst/include/cppad/local/recorder.hpp:15:0,
                 from ../inst/include/cppad/local/ad.hpp:22,
                 from ../inst/include/cppad/cppad.hpp:78,
                 from ../inst/include/FLQuant_base.h:6,
                 from ../inst/include/FLCatch.h:10,
                 from FLCatch.cpp:6:
../inst/include/cppad/local/pod_vector.hpp:41:25: error: redefinition of
'bool CppAD::is_pod() [with Type = unsigned int]'
 template <> inline bool is_pod<size_t>(void)             { return true; }
                         ^
../inst/include/cppad/local/pod_vector.hpp:39:25: note: 'bool
CppAD::is_pod() [with Type = unsigned int]' previously declared here
 template <> inline bool is_pod<unsigned int>(void)       { return true; }
                         ^
make: *** [FLCatch.o] Error 1
Warning: running command 'make -f "Makevars.win" -f
"C:/R/R-33~1.1/etc/i386/Makeconf" -f "C:/R/R-33~1.1/share/make/winshlib.mk"
CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)'
CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)'
SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="FLasher.dll" OBJECTS="FLCatch.o
FLFishery.o FLQuant_base.o FLQuant_multidim.o FLStock.o RcppExports.o
fwdBiol.o fwdControl.o fwdSR.o operating_model.o rcpp_hello_world.o
solver.o tests_FLCatch.o tests_FLFishery.o tests_FLQuant.o
tests_FLQuantAD.o tests_FLQuant_multidim.o tests_FLStock.o
tests_arithmetic_operators.o tests_fwdBiol.o tests_fwdControl.o
tests_fwdSR.o tests_operatingModel.o tests_profiling.o tests_solver.o"' had
status 2
ERROR: compilation failed for package 'FLasher'
* removing 'D:/Profiles/Scott/My Documents/R/win-library/3.3/FLasher'

Thanks in advance for your help with this.

SL

**Comment by iagomosqueira** [comment]
FLasher will only compile on x64. I need to find the way of specifying this in the package so it will attempt to compile on i386. Can you try from 64 bit R?

I have now also added FLasher to [appveyor](https://ci.appveyor.com/project/iagomosqueira/flasher). The package test fails, but it is a know issue at the moment.

**Comment by slarge** [comment]
I am using 64 bit R and have tried to "cheat" by only installing the 64 bit
Rtools toolchain... and the install fails :

* installing *source* package 'FLasher' ...
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/g++  -std=c++0x -I"C:/R/R-33~1.1/include" -DNDEBUG
 -I"D:/Profiles/Scott/My Documents/R/win-library/3.3/Rcpp/include"
-I"d:/Compiler/gcc-4.9.3/local330/include"  -I../inst/include   -O2 -Wall
 -mtune=core2 -c FLCatch.cpp -o FLCatch.o
c:/Rtools/mingw_32/bin/g++: not found

Other ideas?

**Comment by iagomosqueira** [comment]
Not sure why it is still looking for i386. Can you try adding the x64 bin folder to the path instead of the main one? Should be R_HOME/bin/x64/bin.

**Comment by iagomosqueira** [comment]
It seems a clean installation of R 64 and Rtools have solved the issue.
